name: Deploy Application 

on:
  push:
    branches: ["staging"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: travisj/build-number-action@v1
        id: my-project-build-number

      - name: Echo Build Number
        run: echo $BUILD_NUMBER
        env:
          BUILD_NUMBER: ${{ steps.my-project-build-number.outputs.build-number }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laratm:${{BUILD_NUMBER}}
