name: Deploy Application 

on:
  push:
    branches: ["staging"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}